spring:
  application:
    name: gateway
server:
  port: 10005

zuul:
  routes:
    # 面向服务的路由
    provider: #用来区分不同服务的一个名字，可以随便取
      path: /provider/** #zuul网关访问服务的一个路径
      sensitiveHeaders:
      serviceId: server-provider #server-provider 对应的是注册中心的服务的名称

    caller: #用来区分不同服务的一个名字，可以随便取
      path: /caller/** #zuul网关访问服务的一个路径
      sensitiveHeaders:
      serviceId: server-caller #server-caller 对应的是注册中心的服务的名称

    oauth-server: #用来区分不同服务的一个名字，可以随便取
      path: /oauthServer/** #zuul网关访问服务的一个路径
      sensitiveHeaders:
      serviceId: auth2-demo #auth2-demo 对应的是注册中心的服务的名称

    # 传统的路由
    #api-b-url:
      #path: /caller/**
      #由传统的路由模式，我们可以知道用户访问的路由路径为localhost:10215/caller，将服务映射到了http://localhost:10213
      #url: http://localhost:10213/


security:
  auth:
    server: http://127.0.0.1:10008
  oauth2:
    client:
      client-id: client_id
      client-secret: client_secret
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check_token #auth服务中验证token
      #jwt:
        #key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true #显示服务器IP