spring:
  application:
    name: server-caller
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false # 开发过程建议关闭缓存
    servlet:
      content-type: text/html

showImg: file:F:/MyQRCode/
showImgPrefix: /upload/**

#服务端口
server:
  port: 10004

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true


security:
  auth:
    server: http://127.0.0.1:10008
  oauth2:
    client:
      client-id: client_id
      client-secret: client_secret
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check_token #auth服务中验证token
      #jwt:
        #key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

