spring:
  application:
    name: server-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mj_prod?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 2
    host: localhost
    port: 6379
    #password: 1qaz@WSX
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
#    timeout: 100ms

server:
  port: 10007
  servlet:
    context-path: /uaa

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true #\u663E\u793A\u670D\u52A1\u5668IP

security:
  oauth2:
    resource:
      filter-order: 3
#security:
#  oauth2:
#    client:
#      #client-id\u3001client-secret \u8981\u548C\u8BA4\u8BC1\u670D\u52A1\u4E2D\u7684\u914D\u7F6E\u4E00\u81F4
#      client-id: user-client
#      client-secret: user-secret-8888
#      #\u6388\u6743\u7801\u8BA4\u8BC1\u65B9\u5F0F\u9700\u8981\u7684
#      user-authorization-uri: http://localhost:10006/oauth/authorize
#      #\u5BC6\u7801\u6A21\u5F0F\u9700\u8981\u7528\u5230\u7684\u83B7\u53D6 token \u7684\u63A5\u53E3
#      access-token-uri: http://localhost:10006/oauth/token
#    resource:
#      id: user-client
#      user-info-uri: http://localhost:10006/oauth/check_token
#    #\u5F53\u6B64\u670D\u52A1\u7AEF\u63A5\u6536\u5230\u6765\u81EA\u5BA2\u6237\u7AEF\u7AEF\u7684\u8BF7\u6C42\u540E\uFF0C\u9700\u8981\u62FF\u7740\u8BF7\u6C42\u4E2D\u7684 token \u5230\u8BA4\u8BC1\u670D\u52A1\u7AEF\u505A token \u9A8C\u8BC1\uFF0C\u5C31\u662F\u8BF7\u6C42\u7684\u8FD9\u4E2A\u63A5\u53E3
#    authorization:
#      check-token-access: http://localhost:10006/oauth/check_token
#    resource:
#      jwt:
#        key-uri: http://localhost:10006/oauth/token_key
#        key-value: dev
