spring:
  application:
    name: server-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mytables?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  #  mapper文件
  mapper-locations: classpath:mapper/*.xml
  #  实体类
  type-aliases-package: com.cloud.serverprovider.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

showImg: file:F:/MyQRCode/
showImgPrefix: /upload/**
showImgPrefixPath: /upload/
imgPath: F:/MyQRCode/

# 服务端口
server:
  port: 10003

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true


security:
  auth:
    server: http://127.0.0.1:10008
  oauth2:
    client:
      client-id: client_id
      client-secret: client_secret
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check_token #auth服务中验证token
      #jwt:
        #key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

# 配置一个实体类属性
myPojo:
  name: ydx
  age: 22
  like: eat
  addre: xxhuixian
