server:
  port: 10008

spring:
  application:
    name: auth2-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mj_prod?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 2
    host: localhost
    port: 6379
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false # 开发过程建议关闭缓存
    servlet:
      content-type: text/html
  mvc:
    throw-exception-if-no-handler-found: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true #\u663E\u793A\u670D\u52A1\u5668IP
